import = ["~/.config/alacritty/themes/auy_dark.toml"]

[env]
TERM = "xterm-256color"

[window]
opacity = 0.92
blur = true
dimensions = { columns = 200, lines = 85 }
padding = {x = 0, y=0}
dynamic_padding = true
decorations = "Buttonless"

[font]
normal = { family = "JetBrainsMono Nerd Font" }
size = 19
offset = {x = 0, y = 1}

[[keyboard.bindings]]
key = "N"
mods = "Command"
action = "CreateNewWindow"

[[keyboard.bindings]]
key = "F"
mods = "Command"
action = "ToggleFullscreen"
